### ISSUE TITLE
Py4JError("Answer from Java side is empty") while testing

### ISSUE THREAD

**Issue by prakhar21** [databricks/tensorframes#39] opened 2016-06-15 06:49 UTC
I have been experimenting with TensorFrames from quite some days. I have spark-1.6.1 and openjdk7 installed on my ubuntu 14.04 64bit machine. I am using IPython notebook for testing.

`import tensorframes as tfs` command is working perfectly fine, but when i do `tfs.print_schema(df)`, where df is a dataframe. The below error pops recursively till max. depth is reached.

`ERROR:py4j.java_gateway:Error while sending or receiving.
Traceback (most recent call last):
  File "/home/prakhar/utilities/spark-1.6.1/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 746, in send_command
    raise Py4JError("Answer from Java side is empty")
Py4JError: Answer from Java side is empty`

**Comment by tjhunter** [comment] 2016-06-15 17:38
It looks like the spark backend is throwing an error. Can you get the spark logs? I am not familiar with your setup so you will have to figure out where they are located.

Also, how did you build the dataframe?

**Comment by prakhar21** [comment] 2016-06-17 05:54
Spark's working fine. Normal **rdd** transformation and actions are working fine.  I have been using 
$ `IPYTHON_OPTS='notebook' ./bin/pyspark --packages tjhunter:tensorframes:0.2.2-s_2.10` from inside spark directory. 

![screenshot from 2016-06-16 11 30 02](https://cloud.githubusercontent.com/assets/6958949/16106857/e049d2f0-33b5-11e6-90c3-56272c8ec3c3.png)

**Comment by tjhunter** [comment] 2016-06-17 18:13
I could reproduce your bug. For some reason, ipython hides the real exception, which I am pasting below. You are using java 7, which has reached end of life status since a year ago. You should upgrade to java 8, for example by following these instructions:

http://askubuntu.com/questions/521145/how-to-install-oracle-java-on-ubuntu-14-04

Let me know how it goes.

```
Py4JError: Answer from Java side is empty
Exception in thread "Thread-556" java.lang.UnsupportedClassVersionError: org/tensorflow/framework/GraphDef : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
	at java.lang.Class.privateGetPublicMethods(Class.java:2743)
	at java.lang.Class.getMethods(Class.java:1480)
	at py4j.reflection.ReflectionEngine.getMethodsByNameAndLength(ReflectionEngine.java:367)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:319)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:344)
	at py4j.Gateway.invoke(Gateway.java:252)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thunterdb** [comment] 2016-06-27 20:53
@prakhar21 is it still an issue? Otherwise, I am going to close this ticket.

**Closed** 2016-07-07 16:20 UTC
